using System;
using System.Collections.Generic;
using System.Linq;
using Verse;
using RimWorld;
using RimTalk.MemoryPatch;

namespace RimTalk.Memory
{
    /// <summary>
    /// 自动生成Pawn状态常识（新人/老人标识）
    /// 每24小时更新一次，保留玩家手动修改
    /// </summary>
    public static class PawnStatusKnowledgeGenerator
    {
        // 记录每个Pawn上次更新时间
        private static Dictionary<int, int> lastUpdateTicks = new Dictionary<int, int>();
        private const int UPDATE_INTERVAL_TICKS = 60000; // 24小时 = 60000 ticks
        
        /// <summary>
        /// 更新所有殖民者的状态常识（每小时调用一次）
        /// 只更新距离上次更新>=24小时的Pawn
        /// </summary>
        public static void UpdateAllColonistStatus()
        {
            if (!RimTalkMemoryPatchMod.Settings.enablePawnStatusKnowledge)
                return;
            
            var library = MemoryManager.GetCommonKnowledge();
            if (library == null) return;

            int currentTick = Find.TickManager.TicksGame;
            int updatedCount = 0;
            
            foreach (var map in Find.Maps)
            {
                foreach (var pawn in map.mapPawns.FreeColonists)
                {
                    try
                    {
                        // 检查是否需要更新（24小时间隔）
                        int pawnID = pawn.thingIDNumber;
                        
                        if (!lastUpdateTicks.TryGetValue(pawnID, out int lastUpdate))
                        {
                            lastUpdate = 0; // 首次更新
                        }
                        
                        int ticksSinceUpdate = currentTick - lastUpdate;
                        
                        if (ticksSinceUpdate >= UPDATE_INTERVAL_TICKS)
                        {
                            UpdatePawnStatusKnowledge(pawn, library, currentTick);
                            lastUpdateTicks[pawnID] = currentTick;
                            updatedCount++;
                        }
                    }
                    catch (Exception ex)
                    {
                        Log.Error($"[PawnStatus] Error updating status for {pawn.LabelShort}: {ex.Message}");
                    }
                }
            }
            
            if (updatedCount > 0 && Prefs.DevMode)
            {
                Log.Message($"[PawnStatus] Updated {updatedCount} colonist status knowledge entries");
            }
        }

        /// <summary>
        /// 为单个Pawn更新状态常识
        /// 保留玩家的手动修改（重要性、自定义内容等）
        /// </summary>
        public static void UpdatePawnStatusKnowledge(Pawn pawn, CommonKnowledgeLibrary library, int currentTick)
        {
            if (pawn == null || library == null) return;

            try
            {
                // 婴儿阶段（<3岁）不生成状态
                if (pawn.RaceProps != null && pawn.RaceProps.Humanlike)
                {
                    float ageYears = pawn.ageTracker.AgeBiologicalYearsFloat;
                    if (ageYears < 3f)
                    {
                        CleanupPawnStatusKnowledge(pawn);
                        return;
                    }
                }
                
                // 计算入殖时长
                // 注意：TimeAsColonistOrColonyAnimal 记录的是累计在殖民地的时间（ticks）
                // 不是加入时的tick，所以直接使用这个值即可
                int ticksInColony = pawn.records.GetAsInt(RecordDefOf.TimeAsColonistOrColonyAnimal);
                int daysInColony = ticksInColony / GenDate.TicksPerDay;

                // 使用唯一标签
                string statusTag = $"殖民者,{pawn.LabelShort}";
                var existingEntry = library.Entries.FirstOrDefault(e => 
                    e.tag.Contains(pawn.LabelShort) && 
                    e.tag.Contains("殖民者")
                );

                string newContent = GenerateStatusContent(pawn, daysInColony);
                float defaultImportance = GetStatusImportance(daysInColony);

                if (existingEntry != null)
                {
                    // 检查是否为自动生成的内容（没有被玩家编辑）
                    bool isAutoGenerated = !existingEntry.isUserEdited && 
                                          IsAutoGeneratedContent(existingEntry.content);
                    
                    if (isAutoGenerated)
                    {
                        // 只更新自动生成的内容
                        existingEntry.content = newContent;
                        existingEntry.importance = defaultImportance;
                        existingEntry.targetPawnId = pawn.thingIDNumber; // ? 设置为专属
                        
                        if (Prefs.DevMode)
                        {
                            Log.Message($"[PawnStatus] Auto-updated: {pawn.LabelShort} -> {newContent.Substring(0, Math.Min(50, newContent.Length))}...");
                        }
                    }
                    else
                    {
                        // 保护玩家的手动修改
                        if (Prefs.DevMode)
                        {
                            Log.Message($"[PawnStatus] Preserved user edits for {pawn.LabelShort}");
                        }
                    }
                }
                else
                {
                    // 创建新常识
                    var newEntry = new CommonKnowledgeEntry(statusTag, newContent)
                    {
                        importance = defaultImportance,
                        isEnabled = true,
                        isUserEdited = false,
                        targetPawnId = pawn.thingIDNumber // ? 设置为专属于该Pawn
                    };
                    
                    library.AddEntry(newEntry);
                    
                    if (Prefs.DevMode)
                    {
                        Log.Message($"[PawnStatus] Created: {pawn.LabelShort} (importance: {defaultImportance:F2}, targetPawnId: {pawn.thingIDNumber})");
                    }
                }
            }
            catch (Exception ex)
            {
                Log.Error($"[PawnStatus] Failed to update status for {pawn?.LabelShort ?? "Unknown"}: {ex.Message}");
            }
        }

        /// <summary>
        /// 生成状态内容文本
        /// </summary>
        private static string GenerateStatusContent(Pawn pawn, int daysInColony)
        {
            string name = pawn.LabelShort;
            string race = pawn.def?.label ?? "未知种族";
            
            // 根据时长生成不同的描述
            if (daysInColony < 1)
            {
                return $"{name}({race})是今天刚加入殖民地的新成员，对这里还很陌生，不了解殖民地的历史";
            }
            else if (daysInColony < 3)
            {
                return $"{name}({race})在{daysInColony}天前成为殖民者，刚开始熟悉殖民地，不了解之前发生的事";
            }
            else if (daysInColony < 7)
            {
                return $"{name}({race})来到殖民地已经{daysInColony}天，正在适应中，对殖民地的过去不太了解";
            }
            else if (daysInColony < 15)
            {
                return $"{name}({race})已经在殖民地生活了{daysInColony}天，开始融入集体，可能略知一些历史事件";
            }
            else if (daysInColony < 30)
            {
                return $"{name}({race})已经是殖民地的一员（{daysInColony}天），熟悉日常事务，可能略知一些历史但了解有限";
            }
            else if (daysInColony < 60)
            {
                return $"{name}({race})已经在殖民地生活了{daysInColony}天，正式成员，了解近一两个月的事件";
            }
            else
            {
                return $"{name}({race})是殖民地的老成员（{daysInColony}天），见证了殖民地的发展历程";
            }
        }

        /// <summary>
        /// 根据入殖时长计算重要性
        /// </summary>
        private static float GetStatusImportance(int daysInColony)
        {
            if (daysInColony < 7)
            {
                return 1.0f;  // 新成员，非常重要
            }
            else if (daysInColony < 30)
            {
                return 0.85f;  // 适应期，较高重要性
            }
            else
            {
                return 0.70f;  // 老成员，中等重要性
            }
        }

        /// <summary>
        /// 检查内容是否为自动生成的（没有被玩家编辑）
        /// </summary>
        private static bool IsAutoGeneratedContent(string content)
        {
            if (string.IsNullOrEmpty(content))
                return false;
            
            // 检查是否包含自动生成的特征词
            var autoKeywords = new[] 
            { 
                "刚加入", "成为殖民者", "来到殖民地", "生活了", 
                "是殖民地的", "见证了", "天前", "老成员", "新成员"
            };
            
            return autoKeywords.Any(k => content.Contains(k));
        }

        /// <summary>
        /// 清除过期的状态常识（Pawn离开或死亡）
        /// </summary>
        public static void CleanupPawnStatusKnowledge(Pawn pawn)
        {
            if (pawn == null) return;

            var library = MemoryManager.GetCommonKnowledge();
            if (library == null) return;

            var entry = library.Entries.FirstOrDefault(e => 
                e.tag.Contains(pawn.LabelShort) && 
                e.tag.Contains("殖民者")
            );
            
            if (entry != null)
            {
                library.RemoveEntry(entry);
                
                // 清除更新记录
                lastUpdateTicks.Remove(pawn.thingIDNumber);
                
                if (Prefs.DevMode)
                {
                    Log.Message($"[PawnStatus] Removed status for {pawn.LabelShort}");
                }
            }
        }
        
        /// <summary>
        /// 清理更新记录（用于保存/加载）
        /// </summary>
        public static void CleanupUpdateRecords()
        {
            // 移除不存在的Pawn记录
            var allColonistIDs = new HashSet<int>();
            
            foreach (var map in Find.Maps)
            {
                foreach (var pawn in map.mapPawns.FreeColonists)
                {
                    allColonistIDs.Add(pawn.thingIDNumber);
                }
            }
            
            var toRemove = lastUpdateTicks.Keys.Where(id => !allColonistIDs.Contains(id)).ToList();
            foreach (var id in toRemove)
            {
                lastUpdateTicks.Remove(id);
            }
        }
    }
}
